name: Release
on:
  workflow_dispatch:
  push:
    tags:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
    - name: Create executable
      run: scala-cli --power package .
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release delete ${{ github.ref_name }} --yes || true
        gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes 'secret'
